language: "zh_cn"

# 调试设置 (Debug Settings)
debug:
  # 是否启用调试日志 (Enable debug logging)
  enabled: false
  # 是否启用合成调试日志 (Enable crafting debug logging)
  crafting: false

farm:
  # 自动耕地功能
  tilling:
    # Y轴搜索范围设置
    y-axis:
      # 向上搜索的最大距离，-1表示无限
      upper-limit: -1
      # 向下搜索的最大距离，-1表示无限
      lower-limit: -1
    
  # 任务调度设置
  scheduler:
    # 任务执行间隔（单位：刻，20刻=1秒）
    interval: 200
    
  # 施肥设置
  fertilizing:
    # 一次使用的最大骨粉数量
    max-bone-meal: 64