name: Super_Farming
version: '1.0.1'
main: org.little100.super_Farming.Super_Farming
api-version: '1.21'
authors: [ Little_100 ]
description: 谁说锄头没有用？！
website: little100.top
folia-supported: true
commands:
  super_farming:
    description: Main command for the SuperFarming plugin.
    usage: /<command> <lang|reload|editor>
    aliases: [superfarming, sf]
permissions:
  super_farming.admin:
    description: Allows access to all Super_Farming commands.
    default: op
  super_farming.reload:
    description: Allows reloading the plugin's configuration.
    default: op
  super_farming.admin.bypass:
    description: Allows bypassing ownership checks for farms.
    default: op